/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LaboratoryValueNameDropdownDTO,
} from '../models';
import {
    LaboratoryValueNameDropdownDTOFromJSON,
    LaboratoryValueNameDropdownDTOToJSON,
} from '../models';

/**
 * 
 */
export class LaboratoryValueNameControllerApi extends runtime.BaseAPI {

    /**
     */
    async getLaboratoryValueNameDropdownRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LaboratoryValueNameDropdownDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/LaboratoryValueName/dropdown`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LaboratoryValueNameDropdownDTOFromJSON));
    }

    /**
     */
    async getLaboratoryValueNameDropdown(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LaboratoryValueNameDropdownDTO>> {
        const response = await this.getLaboratoryValueNameDropdownRaw(initOverrides);
        return await response.value();
    }

}
