/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LaboratoryReportDTO,
} from '../models';
import {
    LaboratoryReportDTOFromJSON,
    LaboratoryReportDTOToJSON,
} from '../models';

/**
 * 
 */
export class LaboratoryReportControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllReportsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LaboratoryReportDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/LaboratoryReport`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LaboratoryReportDTOFromJSON));
    }

    /**
     */
    async getAllReports(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LaboratoryReportDTO>> {
        const response = await this.getAllReportsRaw(initOverrides);
        return await response.value();
    }

}
