spring:
  datasource:
    url: jdbc:postgresql://dpg-chd6p62k728tp9f51ehg-a.frankfurt-postgres.render.com/nmk
    username: nmk_user
    password: uzt4cfbr5MMXdFMKrcdLyvC58jfFSIdE
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/master-changelog.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-r4r2t64ocsg3g08e.us.auth0.com/
auth0:
  audience: https://dev-r4r2t64ocsg3g08e.us.auth0.com/api/v2/
