/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LaboratoryReportRequest
 */
export interface LaboratoryReportRequest {
    /**
     * 
     * @type {number}
     * @memberof LaboratoryReportRequest
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof LaboratoryReportRequest
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof LaboratoryReportRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof LaboratoryReportRequest
     */
    userId?: number;
}

/**
 * Check if a given object implements the LaboratoryReportRequest interface.
 */
export function instanceOfLaboratoryReportRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LaboratoryReportRequestFromJSON(json: any): LaboratoryReportRequest {
    return LaboratoryReportRequestFromJSONTyped(json, false);
}

export function LaboratoryReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LaboratoryReportRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function LaboratoryReportRequestToJSON(value?: LaboratoryReportRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substr(0,10)),
        'description': value.description,
        'userId': value.userId,
    };
}

