/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDropdownDTO
 */
export interface UserDropdownDTO {
    /**
     * 
     * @type {number}
     * @memberof UserDropdownDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserDropdownDTO
     */
    email?: string;
}

/**
 * Check if a given object implements the UserDropdownDTO interface.
 */
export function instanceOfUserDropdownDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDropdownDTOFromJSON(json: any): UserDropdownDTO {
    return UserDropdownDTOFromJSONTyped(json, false);
}

export function UserDropdownDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDropdownDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserDropdownDTOToJSON(value?: UserDropdownDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
    };
}

